
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.80.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading.Tasks;
using XTC.FMP.MOD.AccessNet.LIB.Proto;

namespace XTC.FMP.MOD.AccessNet.LIB.MVCS
{
    /// <summary>
    /// Point服务模拟类
    /// </summary>
    public class PointServiceMock
    {


        public System.Func<PointOnlineRequest, Task<UuidResponse>>? CallOnlineDelegate { get; set; } = null;

        public System.Func<PointOfflineRequest, Task<UuidResponse>>? CallOfflineDelegate { get; set; } = null;

        public System.Func<PointHeartBeatRequest, Task<UuidResponse>>? CallHeartBeatDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<PointRetrieveResponse>>? CallRetrieveDelegate { get; set; } = null;

        public System.Func<PointListRequest, Task<PointListResponse>>? CallListDelegate { get; set; } = null;

    }
}
