
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.80.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading;
using XTC.FMP.LIB.MVCS;
using XTC.FMP.MOD.AccessNet.LIB.Bridge;

namespace XTC.FMP.MOD.AccessNet.LIB.MVCS
{
    /// <summary>
    /// Point视图层基类
    /// </summary>
    public class PointViewBase : View
    {
        /// <summary>
        /// 带uid参数的构造函数
        /// </summary>
        /// <param name="_uid">实例化后的唯一识别码</param>
        /// <param name="_gid">直系的组的ID</param>
        public PointViewBase(string _uid, string _gid) : base(_uid)
        {
            gid_ = _gid;
        }


        /// <summary>
        /// 刷新Online的数据
        /// </summary>
        /// <param name="_err">错误</param>
        /// <param name="_dto">UuidResponse的数据传输对象</param>
        public virtual void RefreshProtoOnline(Error _err, UuidResponseDTO _dto, object? _context)
        {
            var bridge = getFacade()?.getUiBridge() as IPointUiBridge; 
            if (!Error.IsOK(_err))
            {
                bridge?.Alert(string.Format("errcode_Online_{0}", _err.getCode()), _err.getMessage(), _context);
                return;
            }
            bridge?.RefreshOnline(_dto, _context);
        }

        /// <summary>
        /// 刷新Offline的数据
        /// </summary>
        /// <param name="_err">错误</param>
        /// <param name="_dto">UuidResponse的数据传输对象</param>
        public virtual void RefreshProtoOffline(Error _err, UuidResponseDTO _dto, object? _context)
        {
            var bridge = getFacade()?.getUiBridge() as IPointUiBridge; 
            if (!Error.IsOK(_err))
            {
                bridge?.Alert(string.Format("errcode_Offline_{0}", _err.getCode()), _err.getMessage(), _context);
                return;
            }
            bridge?.RefreshOffline(_dto, _context);
        }

        /// <summary>
        /// 刷新HeartBeat的数据
        /// </summary>
        /// <param name="_err">错误</param>
        /// <param name="_dto">UuidResponse的数据传输对象</param>
        public virtual void RefreshProtoHeartBeat(Error _err, UuidResponseDTO _dto, object? _context)
        {
            var bridge = getFacade()?.getUiBridge() as IPointUiBridge; 
            if (!Error.IsOK(_err))
            {
                bridge?.Alert(string.Format("errcode_HeartBeat_{0}", _err.getCode()), _err.getMessage(), _context);
                return;
            }
            bridge?.RefreshHeartBeat(_dto, _context);
        }

        /// <summary>
        /// 刷新Retrieve的数据
        /// </summary>
        /// <param name="_err">错误</param>
        /// <param name="_dto">PointRetrieveResponse的数据传输对象</param>
        public virtual void RefreshProtoRetrieve(Error _err, PointRetrieveResponseDTO _dto, object? _context)
        {
            var bridge = getFacade()?.getUiBridge() as IPointUiBridge; 
            if (!Error.IsOK(_err))
            {
                bridge?.Alert(string.Format("errcode_Retrieve_{0}", _err.getCode()), _err.getMessage(), _context);
                return;
            }
            bridge?.RefreshRetrieve(_dto, _context);
        }

        /// <summary>
        /// 刷新List的数据
        /// </summary>
        /// <param name="_err">错误</param>
        /// <param name="_dto">PointListResponse的数据传输对象</param>
        public virtual void RefreshProtoList(Error _err, PointListResponseDTO _dto, object? _context)
        {
            var bridge = getFacade()?.getUiBridge() as IPointUiBridge; 
            if (!Error.IsOK(_err))
            {
                bridge?.Alert(string.Format("errcode_List_{0}", _err.getCode()), _err.getMessage(), _context);
                return;
            }
            bridge?.RefreshList(_dto, _context);
        }


        /// <summary>
        /// 获取直系数据层
        /// </summary>
        /// <returns>数据层</returns>
        protected PointModel? getModel()
        {
            if(null == model_)
                model_ = findModel(PointModel.NAME + "." + gid_) as PointModel;
            return model_;
        }

        /// <summary>
        /// 获取直系服务层
        /// </summary>
        /// <returns>服务层</returns>
        protected PointService? getService()
        {
            if(null == service_)
                service_ = findService(PointService.NAME + "." + gid_) as PointService;
            return service_;
        }

        /// <summary>
        /// 获取直系UI装饰层
        /// </summary>
        /// <returns>UI装饰层</returns>
        protected PointFacade? getFacade()
        {
            if(null == facade_)
                facade_ = findFacade(PointFacade.NAME + "." + gid_) as PointFacade;
            return facade_;
        }

        /// <summary>
        /// 直系的MVCS的四个组件的组的ID
        /// </summary>
        protected string gid_ = "";

        /// <summary>
        /// 直系数据层
        /// </summary>
        private PointModel? model_;

        /// <summary>
        /// 直系服务层
        /// </summary>
        private PointService? service_;

        /// <summary>
        /// 直系UI装饰层
        /// </summary>
        private PointFacade? facade_;
    }
}

