
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.AccessNet.LIB.Proto;
using XTC.FMP.MOD.AccessNet.LIB.Bridge;

namespace XTC.FMP.MOD.AccessNet.LIB.MVCS
{

    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoRequest Value;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoResponse Value;
    }



    public class PointOnlineRequestDTO : IDTO
    {
        public PointOnlineRequestDTO(PointOnlineRequest _value)
        {
            Value = _value;    
        }
        public readonly PointOnlineRequest Value;
    }



    public class PointOfflineRequestDTO : IDTO
    {
        public PointOfflineRequestDTO(PointOfflineRequest _value)
        {
            Value = _value;    
        }
        public readonly PointOfflineRequest Value;
    }



    public class PointHeartBeatRequestDTO : IDTO
    {
        public PointHeartBeatRequestDTO(PointHeartBeatRequest _value)
        {
            Value = _value;    
        }
        public readonly PointHeartBeatRequest Value;
    }



    public class PointRetrieveResponseDTO : IDTO
    {
        public PointRetrieveResponseDTO(PointRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly PointRetrieveResponse Value;
    }



    public class PointListRequestDTO : IDTO
    {
        public PointListRequestDTO(PointListRequest _value)
        {
            Value = _value;    
        }
        public readonly PointListRequest Value;
    }



    public class PointListResponseDTO : IDTO
    {
        public PointListResponseDTO(PointListResponse _value)
        {
            Value = _value;    
        }
        public readonly PointListResponse Value;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _value)
        {
            Value = _value;    
        }
        public readonly Status Value;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _value)
        {
            Value = _value;    
        }
        public readonly BlankRequest Value;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _value)
        {
            Value = _value;    
        }
        public readonly BlankResponse Value;
    }



    public class ScopeRequestDTO : IDTO
    {
        public ScopeRequestDTO(ScopeRequest _value)
        {
            Value = _value;    
        }
        public readonly ScopeRequest Value;
    }



    public class ScopeResponseDTO : IDTO
    {
        public ScopeResponseDTO(ScopeResponse _value)
        {
            Value = _value;    
        }
        public readonly ScopeResponse Value;
    }



    public class UuidRequestDTO : IDTO
    {
        public UuidRequestDTO(UuidRequest _value)
        {
            Value = _value;    
        }
        public readonly UuidRequest Value;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _value)
        {
            Value = _value;    
        }
        public readonly UuidResponse Value;
    }



    public class PointEntityDTO : IDTO
    {
        public PointEntityDTO(PointEntity _value)
        {
            Value = _value;    
        }
        public readonly PointEntity Value;
    }



}
