
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading;
using XTC.FMP.LIB.MVCS;

namespace XTC.FMP.MOD.AccessNet.LIB.Bridge
{
    /// <summary>
    /// Point的UI桥接层（协议部分）
    /// 刷新从视图收到的数据
    /// </summary>
    public interface IPointUiProtoBridge : View.Facade.Bridge
    {
        /// <summary>
        /// 全局警告
        /// </summary>
        /// <param name="_code">错误码</param>
        /// <param name="_code">错误信息</param>
        void Alert(string _code, string _message, object? _context);

        /// <summary>
        /// 刷新Online的数据
        /// </summary>
        void RefreshOnline(IDTO _dto, object? _context);


        /// <summary>
        /// 刷新Offline的数据
        /// </summary>
        void RefreshOffline(IDTO _dto, object? _context);


        /// <summary>
        /// 刷新HeartBeat的数据
        /// </summary>
        void RefreshHeartBeat(IDTO _dto, object? _context);


        /// <summary>
        /// 刷新Retrieve的数据
        /// </summary>
        void RefreshRetrieve(IDTO _dto, object? _context);


        /// <summary>
        /// 刷新List的数据
        /// </summary>
        void RefreshList(IDTO _dto, object? _context);


    }
}

